# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
email: jeanette.mumford@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jeanette Mumford - a statistician who cares.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeanettemumford.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mumbrainstats
github_username:  jmumford


# Build settings
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
author:
 # name             : "Your Name"
  #avatar           : "/assets/images/myface_bw.png"
  #bio              : "Statistician who cares"
  location         : "Madison, WI"
  links:
    - label: "Mumford Brain Stats Blog"
      icon: "fab fa-fw fa-tumblr-square"
      url: "https://mumfordbrainstats.tumblr.com/"
    - label: "Mumford Brain Stats Videos"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/c/mumfordbrainstats/videos"
    - label: "@mumbrainstats"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mumbrainstats?lang=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/jmumford"

atom_feed:
  hide: true

